import type { Metadata } from 'next';
import { Ledger, Lexend } from 'next/font/google';

import { cn } from '@/shared/lib/utils';
import { Dialog } from '@/shared/ui/components/atoms';
import { Footer, Header } from '@/shared/ui/components/organisms';
import { CookieConsent } from '@/shared/ui/components/organisms/cookie-consent';

import './globals.css';

const lexend = Lexend({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-lexend',
});

const ledger = Ledger({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-ledger',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased', lexend.variable, ledger.variable)}>
        <Header />
        {children}
        <Footer />
        <Dialog />
        <CookieConsent />
      </body>
    </html>
  );
}
