import type { Metadata } from 'next';
import { Ledger } from 'next/font/google';

import { cn } from '@/shared/lib/utils';

import './globals.css';

const ledger = Ledger({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-ledger',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased', ledger.variable)}>{children}</body>
    </html>
  );
}
