import type { Metadata } from 'next';
import { Ledger, Lexend } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Toaster } from 'sonner';

import { cn } from '@/shared/lib/utils';
import { Dialog } from '@/shared/ui/components/atoms/dialog';
import { Preloader } from '@/shared/ui/components/molecules/preloader';
import { CookieConsent } from '@/shared/ui/components/organisms/cookie-consent';
import { Footer } from '@/shared/ui/components/organisms/footer';
import { Header } from '@/shared/ui/components/organisms/header';

import './globals.css';

const lexend = Lexend({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-lexend',
});

const ledger = Ledger({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-ledger',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleAnalytics gaId="G-M2QJY5QBW1" />
      <body className={cn('antialiased', lexend.variable, ledger.variable)}>
        <NextIntlClientProvider>
          <Header />
          {children}
          <Footer />
          <Dialog />
          <CookieConsent />
          <Toaster />
          <Preloader />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
